### PR TITLE
PHP 8.1 tests

### PR DESCRIPTION
**Pull request by mikemadison13**

### CODE REVIEW

**Comment by danepowell** [comment]
If we do this, won't new projects get Drupal 10 OOTB? We don't want that. Or will prefer-stable: true prevent that?

**Comment by mikemadison13** [comment]
that might be the case if they are running PHP 8.1. I don't THINK it will be a factor at PHP 8.x or below (given that Drupal 10 requires PHP 8.1 and won't install otherwise).

**Comment by danepowell** [comment]
@mikemadison13 what's the point of doing this now? What's the business value?

I tested locally and confirmed that the config platform php restriction in composer.json will force Drupal 9. But by that same token, it makes this PR kind of pointless. If someone is editing their composer.json to remove that restriction, they could just as easily require Drupal 10 at the same time.

**Comment by mikemadison13** [comment]
@danepowell it probably makes sense to just add the PHP 8.1.x test for now and not the drupal 10.x. Thoughts?

**Comment by danepowell** [comment]
I agree, we should revisit this once D10 is closer to stable.

**Pull request merged**
